name: Bank Affiliate Bot

on:
  schedule:
    - cron: "40 0 * * *"   # Build queue at 06:10 IST (00:40 UTC)
    - cron: "15 6 * * *"   # Post 1 at 11:45 IST (06:15 UTC)
    - cron: "15 12 * * *"  # Post 2 at 17:45 IST (12:15 UTC)
    - cron: "15 18 * * *"  # Post 3 at 23:45 IST (18:15 UTC)
  workflow_dispatch:

jobs:
  build-queue:
    # Run when manually triggered OR at the 00:40 UTC cron
    if: github.event_name == 'workflow_dispatch' || github.event.schedule == '40 0 * * *'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests
          fi

      - name: Build daily queue
        env:
          DATA_FILE: data/bank_offers.enriched.json
          FALLBACK_DATA_FILE: data/bank_offers.json
          SCHEDULE_FILE: data/schedule_config.json
          QUEUE_FILE: data/today_queue.json
          STATE_FILE: data/schedule_state.json
        run: |
          python scripts/build_schedule.py

      - name: Commit queue/state
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add data/today_queue.json data/schedule_state.json
            git commit -m "chore: build today queue"
            git push
          else
            echo "No changes."
          fi

  post:
    # Run when manually triggered OR at any of the three posting crons
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event.schedule == '15 6 * * *' ||
      github.event.schedule == '15 12 * * *' ||
      github.event.schedule == '15 18 * * *'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests
          fi

      - name: Post one item to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          DATA_FILE: data/bank_offers.json
          ENRICHED_FILE: data/bank_offers.enriched.json
          QUEUE_FILE: data/today_queue.json
          HISTORY_FILE: data/post_history.json
        run: |
          python scripts/post_to_telegram.py

      - name: Commit history/queue updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add data/post_history.json data/today_queue.json
            git commit -m "chore: posted one item"
            git push
          else
            echo "No changes."
          fi
