name: Bank Affiliate Bot

on:
  schedule:
    - cron: "40 0 * * *"   # Build queue at 06:10 IST (00:40 UTC)
    - cron: "15 6 * * *"   # Post 1 at 11:45 IST (06:15 UTC)
    - cron: "15 12 * * *"  # Post 2 at 17:45 IST (12:15 UTC)
    - cron: "15 18 * * *"  # Post 3 at 23:45 IST (18:15 UTC)
  workflow_dispatch:
    inputs:
      day:
        description: "Weekday to build & post (manual only)"
        required: false
        default: "auto"
        type: choice
        options:
          - auto
          - mon
          - tue
          - wed
          - thu
          - fri
          - sat
          - sun

jobs:
  build-queue:
    # Run on morning cron OR any manual run (to allow building queue for selected day)
    if: github.event_name == 'workflow_dispatch' || github.event.schedule == '40 0 * * *'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests
          fi

      # Build the queue. If manual with a chosen day, we pass DAY_OVERRIDE environment.
      - name: Build queue (auto or manual override)
        env:
          DATA_FILE: data/bank_offers.enriched.json
          FALLBACK_DATA_FILE: data/bank_offers.json
          SCHEDULE_FILE: data/schedule_config.json
          QUEUE_FILE: data/today_queue.json
          STATE_FILE: data/schedule_state.json
          DAY_OVERRIDE: ${{ inputs.day }}
        run: |
          # Export DAY_OVERRIDE only if manual and not 'auto'
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ "${{ inputs.day }}" != "auto" ]; then
            export DAY_OVERRIDE="${{ inputs.day }}"
          else
            unset DAY_OVERRIDE
          fi
          python scripts/build_schedule.py

      - name: Commit queue/state (robust)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          CHANGED=0
          if [ -f "data/today_queue.json" ]; then
            git add data/today_queue.json
            CHANGED=1
          fi
          if [ -f "data/schedule_state.json" ]; then
            git add data/schedule_state.json
            CHANGED=1
          fi
          if [ "$CHANGED" -eq 1 ]; then
            if ! git diff --cached --quiet; then
              git commit -m "chore: build queue (${{ inputs.day || 'auto' }})"
              git push || echo "No push needed."
            else
              echo "No staged changes."
            fi
          else
            echo "No files to commit."
          fi

  post:
    # Run when manually triggered OR at any of the three posting crons
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event.schedule == '15 6 * * *' ||
      github.event.schedule == '15 12 * * *' ||
      github.event.schedule == '15 18 * * *'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests
          fi

      # Normal scheduled run posts ONE item.
      - name: Post one item to Telegram (scheduled)
        if: github.event_name != 'workflow_dispatch'
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          DATA_FILE: data/bank_offers.json
          ENRICHED_FILE: data/bank_offers.enriched.json
          QUEUE_FILE: data/today_queue.json
          HISTORY_FILE: data/post_history.json
        run: |
          python scripts/post_to_telegram.py

      # Manual run: after building (possibly for chosen day), post ALL items for that day.
      - name: Post all items for selected day (manual only)
        if: github.event_name == 'workflow_dispatch'
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          DATA_FILE: data/bank_offers.json
          ENRICHED_FILE: data/bank_offers.enriched.json
          QUEUE_FILE: data/today_queue.json
          HISTORY_FILE: data/post_history.json
        run: |
          # Loop until queue empties or up to a safe upper bound
          n=0
          while [ $n -lt 20 ]; do
            if [ ! -s "data/today_queue.json" ]; then
              echo "Queue empty, stopping."
              break
            fi
            python scripts/post_to_telegram.py || true
            n=$((n+1))
            sleep 3
          done

      - name: Commit history/queue updates (robust)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          CHANGED=0
          if [ -f "data/post_history.json" ]; then
            git add data/post_history.json
            CHANGED=1
          fi
          if [ -f "data/today_queue.json" ]; then
            git add data/today_queue.json
            CHANGED=1
          fi
          if [ "$CHANGED" -eq 1 ]; then
            if ! git diff --cached --quiet; then
              git commit -m "chore: post updates (${{ inputs.day || 'auto' }})"
              git push || echo "No push needed."
            else
              echo "No staged changes."
            fi
          else
            echo "No files to commit."
          fi
